//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dearCurics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuricsEntities : DbContext
    {
        public CuricsEntities()
            : base("name=CuricsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_specialization> admin_specialization { get; set; }
        public virtual DbSet<general_setting> general_setting { get; set; }
        public virtual DbSet<doctor_price_payment> doctor_price_payment { get; set; }
        public virtual DbSet<doctor_work_experience> doctor_work_experience { get; set; }
        public virtual DbSet<doctor> doctors { get; set; }
    }
}
