//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dearCurics
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_price_payment
    {
        public int doctor_id { get; set; }
        public int price_id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
