//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dearCurics
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_setting
    {
        public int id { get; set; }
        public string site_title { get; set; }
    }
}
